// Generated by scripts/build-dist.ts at release time.
// Committed as a stub so normal `bun run build` works without running build:dist first.
export const VERSION = "0.0.0";
export const PACKAGE_NAME = "@iquantum/cli";
