#!/usr/bin/env bun
/**
 * Production bundle script. Run via `bun run build:dist`.
 *
 * 1. Reads the version from iquantum-cli/package.json
 * 2. Writes iquantum-cli/src/version.ts with the real version
 * 3. Bundles daemon → iquantum-cli/dist/daemon.js
 * 4. Bundles CLI   → iquantum-cli/dist/bin.js
 * 5. Makes bin.js executable
 */

import { chmod, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const cliDir = join(root, "iquantum-cli");
const distDir = join(cliDir, "dist");

// 1. Read version
const cliPkg = (await Bun.file(join(cliDir, "package.json")).json()) as {
  version: string;
};
const version = cliPkg.version;
console.log(`Building iquantum v${version}…`);

// 2. Write version.ts
await writeFile(
  join(cliDir, "src", "version.ts"),
  [
    "// Generated by scripts/build-dist.ts — do not edit manually.",
    `export const VERSION = "${version}";`,
    `export const PACKAGE_NAME = "@iquantum/cli";`,
    "",
  ].join("\n"),
  "utf8",
);
console.log(`  wrote src/version.ts (${version})`);

// 3. Create dist dir
await mkdir(distDir, { recursive: true });

// 4. Bundle daemon
const daemonResult = await Bun.build({
  entrypoints: [join(root, "iquantum-daemon", "src", "index.ts")],
  outdir: distDir,
  naming: "daemon.js",
  target: "bun",
  minify: true,
  external: ["bun:sqlite", "bun:ffi"],
});
if (!daemonResult.success) {
  for (const log of daemonResult.logs) console.error(log);
  process.exit(1);
}
const daemonSize = (daemonResult.outputs[0]?.size ?? 0 / 1024).toFixed(0);
console.log(`  built dist/daemon.js (${daemonSize} KB)`);

// 5. Bundle CLI bin
const cliResult = await Bun.build({
  entrypoints: [join(cliDir, "src", "index.ts")],
  outdir: distDir,
  naming: "bin.js",
  target: "bun",
  minify: true,
});
if (!cliResult.success) {
  for (const log of cliResult.logs) console.error(log);
  process.exit(1);
}
const cliSize = (cliResult.outputs[0]?.size ?? 0 / 1024).toFixed(0);
console.log(`  built dist/bin.js (${cliSize} KB)`);

// 6. Make bin executable
await chmod(join(distDir, "bin.js"), 0o755);

console.log(`Done. dist/ is ready for npm publish.`);
