name: Daily Awesome Lists Update

on:
  schedule:
    # Run daily at midnight UTC and 1 AM UTC to ensure it runs
    - cron: '0 0 * * *'
    - cron: '0 1 * * *'
  workflow_dispatch:
    # Allow manual trigger

permissions:
  contents: write  # Needed to push changes to the repo

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper commits
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown beautifulsoup4
          
      - name: Run update script
        run: python scripts/main.py
        
      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions Bot"
          
      - name: Commit and push if there are changes
        run: |
          git add data/awesome-lists.json data/metadata.json
          git diff --staged --quiet || (git commit -m "Daily update: $(date +'%Y-%m-%d')" && git push)
      
      - name: Debug information
        if: always()
        run: |
          echo "Workflow completed at: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          ls -la
          ls -la .github/workflows/
          cat .github/workflows/daily-update.yml
